version: "3"
services:
  db:
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=tp1_grupo10"
    ports:
      - "3306:3306"