services:
  # Base de datos MySQL para Integrador 2 (JPA standalone)
  mysql:
    image: mysql:8.0
    container_name: inte_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mibase
      MYSQL_USER: integrador
      MYSQL_PASSWORD: integrador123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_setup.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
