

### Listar usuarios
GET http://localhost:8081/api/estudiantes

### a) Dar de Alta Usuario
POST http://localhost:8081/api/estudiantes
Content-Type: application/json

{
  "dni": 45821369,
  "nombre": "Ivann",
  "apellido": "Almestro",
  "edad": 25,
  "genero": "Masculino",
  "ciudadDeResidencia": "Tandil",
  "numeroLU": "12345"
}

### Eliminar estudiante
DELETE http://localhost:8081/api/estudiantes/45821369

### b) Matricular estudiante
POST http://localhost:8081/api/carreras/3/matricular/45821369

### c) Recuperar todos los estudiantes (con ordenamiento simple)
GET http://localhost:8081/api/estudiantes?sort=apellido,asc
